<?php
/**
 * @var $block \Lipscore\RatingsReviews\Block\Widget\Service
 */
?>
<div class="lipscore-service-ai-summary"></div>

<?php if ($block->getLipscoreCss()): ?>
    <style>
        <?= /* @noEscape */ $block->getLipscoreCss() ?>
    </style>
<?php endif; ?>

<?php if ($block->getLipscoreJs()): ?>
    <script>
        <?= /* @noEscape */ $block->getLipscoreJs() ?>
    </script>
<?php endif; ?>
