<?php
/**
 * @var $block \Lipscore\RatingsReviews\Block\Widget\Service
 */
?>
<div class="lipscore-rating-distribution" style="display:<?= $block->getDefaultDisplay() ?>;" <?= $block->getProductWidgetAttributes() ?>></div>

<?php if ($block->getLipscoreCss()) : ?>
    <style>
        <?= $block->getLipscoreCss() ?>
    </style>
<?php endif; ?>

<?php if ($block->getLipscoreJs()) : ?>
    <script>
        <?= $block->getLipscoreJs() ?>
    </script>
<?php endif; ?>
