<?php
/**
 * @var $block \Lipscore\RatingsReviews\Block\Widget\Service
 */
?>
<div class="lipscore-service-review-badge-small-long <?= $escaper->escapeHtmlAttr($block->getBadgeWidgetOptions()) ?>"
     style="display:<?= $escaper->escapeHtmlAttr($block->getDefaultDisplay()) ?>;"
     <?= /* @noEscape */ $block->getSharedWidgetAttributes() ?>>
</div>

<?php if ($block->getLipscoreCss()): ?>
    <style>
        <?= /* @noEscape */ $block->getLipscoreCss() ?>
    </style>
<?php endif; ?>

<?php if ($block->getLipscoreJs()): ?>
    <script>
        <?= /* @noEscape */ $block->getLipscoreJs() ?>
    </script>
<?php endif; ?>
