<?php
/**
 * @var $block \Lipscore\RatingsReviews\Block\Widget\Service
 */
?>
<div id="lipscore-service-review-badge-sticky" class="lipscore-service-review-badge-sticky"
     style="display:<?= $escaper->escapeHtmlAttr($block->getDefaultDisplay()) ?>;">
</div>

<?php if ($block->getLipscoreCss()): ?>
    <style>
        <?= /* @noEscape */ $block->getLipscoreCss() ?>
    </style>
<?php endif; ?>

<?php if ($block->getLipscoreJs()): ?>
    <script>
        <?= /* @noEscape */ $block->getLipscoreJs() ?>
    </script>
<?php endif; ?>
