<?php
/**
 * @var $block \Lipscore\RatingsReviews\Block\Widget\Product
 */
?>
<div class="lipscore-rating-big" style="display:<?= $escaper->escapeHtmlAttr($block->getDefaultDisplay()) ?>;"
    <?= /* @noEscape */ $block->getLsProductAttrs() ?>>
</div>

<?php if ($block->getLipscoreProductCss()): ?>
    <style>
        <?= /* @noEscape */ $block->getLipscoreProductCss() ?>
    </style>
<?php endif; ?>

<?php if ($block->getLipscoreProductJs()): ?>
    <script>
        <?= /* @noEscape */ $block->getLipscoreProductJs() ?>
    </script>
<?php endif; ?>
