<?php
/**
 * @var $block Lipscore\RatingsReviews\Block\Product\QA
 */
?>
<?php if ($block->getLsProductAttrs()) { ?>
    <div style="display: none !important;"><?= $escaper->escapeHtml(__('Q&A')) ?></div>
    <div id="lipscore-question-post" <?= /* @noEscape */ $block->getLsProductAttrs() ?>></div>
    <div id="lipscore-question-list" <?= /* @noEscape */ $block->getLsProductAttrs() ?>></div>
<?php } ?>
