<?php
/**
 * @var $block \Lipscore\RatingsReviews\Block\Product\ReviewRenderer
 */
?>
<?php if ($block->getLsProductAttrs()) { ?>
    <div class="product-reviews-summary
        <?= $block->getIsShortType() ? 'short ' : '' ?>mg-lipscore-rating-wrapper">
        <div class="rating-summary">
            <div <?= /* @noEscape */ $block->getRatingType() ?>
                 <?= /* @noEscape */ $block->getLsProductAttrs() ?>>
            </div>
        </div>
     </div>
<?php } ?>
